// generated by tools/gen-mission-images.mjs, do not edit by hand
// the shot showing where each unmarked objective actually is, keyed by mission id

export interface MissionSpot {
  /** small file for the grid card, reused by the lightbox thumbnail strip */
  src: string;
  /** full size for the lightbox viewer */
  full: string;
  label: string;
}

/** shape of the shots once the roblox topbar is cropped off, for the card slot */
export const SPOT_ASPECT = '128 / 67';

export const MISSION_SPOTS: Record<string, MissionSpot[]> = {
  "WeissGift2": [
    {
      "src": "/missions/WeissGift2/EuroDeli.webp",
      "full": "/missions/WeissGift2/EuroDeli@full.webp",
      "label": "Euro Deli"
    },
    {
      "src": "/missions/WeissGift2/FlutonMarket.webp",
      "full": "/missions/WeissGift2/FlutonMarket@full.webp",
      "label": "Fluton Market"
    },
    {
      "src": "/missions/WeissGift2/FreshStopSupermarket_1.webp",
      "full": "/missions/WeissGift2/FreshStopSupermarket_1@full.webp",
      "label": "Fresh Stop Supermarket 1"
    },
    {
      "src": "/missions/WeissGift2/FreshStopSupermarket_2.webp",
      "full": "/missions/WeissGift2/FreshStopSupermarket_2@full.webp",
      "label": "Fresh Stop Supermarket 2"
    }
  ],
  "WeissGift1": [
    {
      "src": "/missions/WeissGift1/DesignerHandbag.webp",
      "full": "/missions/WeissGift1/DesignerHandbag@full.webp",
      "label": "Designer Handbag"
    }
  ],
  "ShadyBiz1": [
    {
      "src": "/missions/ShadyBiz1/card1.webp",
      "full": "/missions/ShadyBiz1/card1@full.webp",
      "label": "Keycard 1"
    },
    {
      "src": "/missions/ShadyBiz1/card2.webp",
      "full": "/missions/ShadyBiz1/card2@full.webp",
      "label": "Keycard 2"
    },
    {
      "src": "/missions/ShadyBiz1/card3.webp",
      "full": "/missions/ShadyBiz1/card3@full.webp",
      "label": "Keycard 3"
    },
    {
      "src": "/missions/ShadyBiz1/goldbar1.webp",
      "full": "/missions/ShadyBiz1/goldbar1@full.webp",
      "label": "Silver bars 1"
    },
    {
      "src": "/missions/ShadyBiz1/goldbar2.webp",
      "full": "/missions/ShadyBiz1/goldbar2@full.webp",
      "label": "Silver bars 2"
    },
    {
      "src": "/missions/ShadyBiz1/goldbar3.webp",
      "full": "/missions/ShadyBiz1/goldbar3@full.webp",
      "label": "Silver bars 3"
    }
  ],
  "Journalist4": [
    {
      "src": "/missions/Journalist4/harddrive.webp",
      "full": "/missions/Journalist4/harddrive@full.webp",
      "label": "Harddrive"
    },
    {
      "src": "/missions/Journalist4/ledger.webp",
      "full": "/missions/Journalist4/ledger@full.webp",
      "label": "Ledger"
    }
  ],
  "Defector2": [
    {
      "src": "/missions/Defector2/smartphone.webp",
      "full": "/missions/Defector2/smartphone@full.webp",
      "label": "Smartphone"
    }
  ],
  "Eye1": [
    {
      "src": "/missions/Eye1/case.webp",
      "full": "/missions/Eye1/case@full.webp",
      "label": "Case"
    }
  ],
  "Kismet2": [
    {
      "src": "/missions/Kismet2/drive.webp",
      "full": "/missions/Kismet2/drive@full.webp",
      "label": "Drive"
    }
  ],
  "Kismet3": [
    {
      "src": "/missions/Kismet3/1.webp",
      "full": "/missions/Kismet3/1@full.webp",
      "label": "Variant 1"
    },
    {
      "src": "/missions/Kismet3/2.webp",
      "full": "/missions/Kismet3/2@full.webp",
      "label": "Variant 2"
    },
    {
      "src": "/missions/Kismet3/3.webp",
      "full": "/missions/Kismet3/3@full.webp",
      "label": "Variant 3"
    },
    {
      "src": "/missions/Kismet3/4.webp",
      "full": "/missions/Kismet3/4@full.webp",
      "label": "Variant 4"
    },
    {
      "src": "/missions/Kismet3/5.webp",
      "full": "/missions/Kismet3/5@full.webp",
      "label": "Variant 5"
    },
    {
      "src": "/missions/Kismet3/6.webp",
      "full": "/missions/Kismet3/6@full.webp",
      "label": "Variant 6"
    },
    {
      "src": "/missions/Kismet3/7.webp",
      "full": "/missions/Kismet3/7@full.webp",
      "label": "Variant 7"
    }
  ],
  "ResearchFellow2": [
    {
      "src": "/missions/ResearchFellow2/archiveKey.webp",
      "full": "/missions/ResearchFellow2/archiveKey@full.webp",
      "label": "Archive Key"
    },
    {
      "src": "/missions/ResearchFellow2/EmployeeInformation.webp",
      "full": "/missions/ResearchFellow2/EmployeeInformation@full.webp",
      "label": "Employee Information"
    }
  ],
  "ResearchFellow3": [
    {
      "src": "/missions/ResearchFellow3/SafeKey1.webp",
      "full": "/missions/ResearchFellow3/SafeKey1@full.webp",
      "label": "Safe key 1"
    },
    {
      "src": "/missions/ResearchFellow3/SafeKey2.webp",
      "full": "/missions/ResearchFellow3/SafeKey2@full.webp",
      "label": "Safe key 2"
    },
    {
      "src": "/missions/ResearchFellow3/SafeKey3.webp",
      "full": "/missions/ResearchFellow3/SafeKey3@full.webp",
      "label": "Safe key 3"
    }
  ],
  "DeepEnd1": [
    {
      "src": "/missions/DeepEnd1/ResearchGateKey.webp",
      "full": "/missions/DeepEnd1/ResearchGateKey@full.webp",
      "label": "Research Gate Key"
    }
  ],
  "ResearchFellow4": [
    {
      "src": "/missions/ResearchFellow4/RefrigeratorKey.webp",
      "full": "/missions/ResearchFellow4/RefrigeratorKey@full.webp",
      "label": "Refrigerator Key"
    }
  ],
  "FixerIntro": [
    {
      "src": "/missions/FixerIntro/FixersGift.webp",
      "full": "/missions/FixerIntro/FixersGift@full.webp",
      "label": "Fixers Gift"
    }
  ],
  "Gaming1": [
    {
      "src": "/missions/Gaming1/1.webp",
      "full": "/missions/Gaming1/1@full.webp",
      "label": "Variant 1"
    },
    {
      "src": "/missions/Gaming1/2.webp",
      "full": "/missions/Gaming1/2@full.webp",
      "label": "Variant 2"
    },
    {
      "src": "/missions/Gaming1/3.webp",
      "full": "/missions/Gaming1/3@full.webp",
      "label": "Variant 3"
    },
    {
      "src": "/missions/Gaming1/4.webp",
      "full": "/missions/Gaming1/4@full.webp",
      "label": "Variant 4"
    },
    {
      "src": "/missions/Gaming1/5.webp",
      "full": "/missions/Gaming1/5@full.webp",
      "label": "Variant 5"
    }
  ]
};

export function spotsFor(missionId: string): MissionSpot[] {
  return MISSION_SPOTS[missionId] ?? [];
}
